language: rust
rust:
- stable
env:
  global:
  - PROJECT_NAME=kctl
matrix:
  fast_finish: true
  include:
  - os: linux
    rust: stable
    env: TARGET=x86_64-linux
  - os: osx
    rust: stable
    env: TARGET=x86_64-darwin
script:
  - cargo build --verbose --all
  - cargo test --verbose --all
before_deploy:
  - cargo build --release
  - mv ./target/release/kctl ./
  - tar cvfz $PROJECT_NAME-$TRAVIS_TAG-$TARGET.tar.gz ./kctl
  - PREVIOUS_TAG=$(git tag | tail -2 | head -1)
  - echo 'Changelog:'
  - git log ${PREVIOUS_TAG}..${TRAVIS_TAG} --oneline
  - export GITHUB_RELEASE_NAME="v${TRAVIS_TAG}"
deploy:
  provider: releases
  api_key:
    secure: DEpQ6NENrFp6YjUFhIRiwBzmNd9DsYPfwELtk2K7EQMfyO8Kqs2Vfqo6zJiAUjhy23cnVHasRrc3Vbu1SWONjGo2R6KOYXbO7FKZtzpa816+GbduPQ4mFS2isoNaPBnyWjpbNovQZmzxGgS2KXU33BxhWAym5mpQMw8WITme0H0uP2eKKT4vvdqnqFSP5eNIMqh7k68lCg/ljSterOXNbgo9HsL9KbGFOiueMGpv4U1IfGVPtFkP4JtwV44yfBW7/5OyICSvwMcGiQ5NuuaUWtvOQS47PEpSCbw+6cuo+7hbd9ZKDjyQBeNbZu+TeZRa0/7AZ83DGlHgFp/eDa3PhoppUGMky0movYynOZi0/IHRRDAmhVTiVzX2u/SdmiYFXDjrDL1PQr4x0AvHXejZOjcclVJJ69PikebNDRG93KAwVzcklJhRTyFU2iazyAp7zpRejVYJydroyFT4nmVgMHNn2smxhomTb+buaB/m7ctj09+XiD+tIl1N+TWiGsMzOtq7ipkPgjIz8NnGmoEsK+XISBnbmpPRYAfdwPxe/+QbyltWUtlhPRkNZ+NCzKFIX6vPBI0hvjDP9kb1q0di7d9O6pvOleX11JOYs3Z8UXXPCkLR4di9d4sbJRbsb7TD2LUPUUYZWA0IMAAnb2XQFDJk9OzzMwBD7HmAj1JoMeA=
  file: '$PROJECT_NAME-$TRAVIS_TAG-$TARGET.tar.gz'
  skip_cleanup: true
  on:
    repo: alaminopu/kctl
    tags: true
